// <auto-generated />
using BSDigital.MetaExchange.Core.Db.EfCore.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSDigital.MetaExchange.Core.Db.EfCore.SQLite.Migrations
{
    [DbContext(typeof(MetaExchangeDbContext))]
    partial class MetaExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("BSDigital.MetaExchange.Core.Db.EfCore.SQLite.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtcBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EurBalance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });
#pragma warning restore 612, 618
        }
    }
}
